
sudo apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    gnupg \
    wget \
    curl \
    net-tools \
    make \
    git \
    zlib1g-dev \
    libssl-dev \
    gperf \
    cmake \
    clang \
    libc++-dev \
    libc++abi-dev \
    php-cli \
    g++ \
    ninja-build \
    pkg-config \
    libgtk-3-dev \
    liblzma-dev \
    xz-utils \
    unzip \
    openjdk-11-jdk \
    xvfb \ 
    libwebp-dev \
    ubuntu-restricted-extras \
    ffmpeg \
    libmpv-dev \
    mpv \
    libwebkit2gtk-4.0-dev \
    ffmpegthumbnailer \
    make \
    autoconf \
    automake \
    libtool \
    pkg-config \
    gcc \
    libsonic-dev \
    ronn \
    kramdown \
    libpcaudio-dev \ 
    gstreamer1.0-plugins-bad \ 
    libsdl2-dev \ 
    libc++1 \
    gir1.2-clutter-1.0 \ 
    python-is-python3 \ 
    linux-tools-common \
    linux-tools-generic
