[program:menfess-telegram-bot]
process_name=%(program_name)s_%(process_num)02d
command=/root/telegram_menfess/menfess_telegram-main/run.sh
autostart=true
autorestart=true
user=root
numprocs=1
redirect_stderr=true
stdout_logfile=/root/telegram_menfess/menfess_telegram-main/worker.log
