
name: AutoMation
on:
  # 🌏 Think about the planet! No need to update stats too frequently
  schedule: [{cron: "0 0 */1 * *"}]
  # 💡 The following line lets you run workflow manually from the action tab!
  workflow_dispatch:
jobs:
  metrics:
    runs-on: ubuntu-20.04
    steps:

      # Readme Profile 
      - name: 🦑 Achievements
        # if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        continue-on-error: true
        with:
          filename: achievements.svg
          token: ${{ secrets.TOKEN }}
          base: ""
          output_action: gist
          committer_gist: ${{ secrets.GIST }}
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_fortune: yes

      - name: 🦑 Sponsors
        # if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        continue-on-error: true
        with:
          filename: sponsors.svg
          token: ${{ secrets.TOKEN }}
          base: ""
          output_action: gist
          committer_gist: ${{ secrets.GIST }}
          plugin_sponsors: yes
          plugin_sponsors_past: yes

      - name: 🦑 General
        # if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        continue-on-error: true
        with:
          filename: general.svg
          token: ${{ secrets.TOKEN }}
          base: header
          base_indepth: yes
          config_order: base.header, isocalendar, languages, notable, discussions, topics
          output_action: gist
          committer_gist: ${{ secrets.GIST }}
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot, vue, scala, c, c++, python, ejs
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_sections: most-used, recently-used
          plugin_languages_indepth: yes
          plugin_languages_limit: 2
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons
          plugin_notable: yes
          plugin_discussions: yes

      - name: Readme Profile Youtube
        continue-on-error: true
        uses: DenverCoder1/github-readme-youtube-cards@main
        with:
          channel_id: UC928-F8HenjZD1zNdMY42vA
