name: Build youtube
on: [workflow_dispatch]
jobs:
  build:
    name: Build Youtube
    runs-on: ubuntu-latest
    steps:
      - name: Readme Update
        uses: azkadev/readme_update@v0.0.0.0-alpha
 
