name: GitHub Readme YouTube Cards
on: [workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: DenverCoder1/github-readme-youtube-cards@main
        with:
          channel_id: UC928-F8HenjZD1zNdMY42vA
